### ISSUE TITLE
Dragging & dropping a checklist item generates no actions, even on webhooks

### ISSUE THREAD

**Issue by ludable** [trello/api-docs#102]
Steps to reproduce:

- Set up a webhook listener on a board.
- Create a card with two checklists, add an item to one of the checklists.
- Drag & drop the item between the checklists.

Result: no actions are received on the webhook. This is inconsistent with adding or removing the checklist item, and can cause applications to miss state changes (e.g. checklist complete / incomplete). No actions appear in the action history either.

**Comment by bentleycook** [comment]
Good catch. Looks like it is doing a PUT on a checklist item. I'll put a ticket in with the server team for this.
```
**Request URL:** https://trello.com/1/cards/58dbaaf4cf60306cc9cb9df0/checklist/58f6353f6cb98c22ef393335/checkItem/58f635405a3479f4839a123c
**Request Method:** PUT
**Query Params:** 
  _pos:_ 34006
  _idChecklist:_ 58f662cfc8432c5d03e1b6b2
```

**Comment by leonardn** [comment]
Got the same issue.

**Comment by bentleycook** [comment]
@ludable We should now be sending an `updateCheckItem` action on the webhook. Can you give it a try?

**Comment by ludable** [comment]
@bentleycook Yup, getting lots of updateCheckItem:pos actions for the last few hours. Thanks!
