### ISSUE TITLE
Icons in card detail badges

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#104]
Hi, for our power-up, we'd like to be able to use an icon along with a card detail badge. For us, we hope that the icon will call attention to the badge and give the user more context for it.

Ideally the icon would be to the left of the text of the badge (below the label) similar to the checkbox on the due date badge.

![](https://cloud.githubusercontent.com/assets/8588/25104026/a6f51ff6-2373-11e7-821a-a427da6fbcb7.png)

**Comment by bentleycook** [comment]
<img width="815" alt="screen shot 2017-04-18 at 5 25 03 pm" src="https://cloud.githubusercontent.com/assets/1723339/25139023/60fe1dba-245c-11e7-98fb-df9804ac7be6.png">

Just to confirm we're on the same page, you'd eventually want your card back to look something like this?

**Comment by bentleycook** [comment]
We've tentatively added this to the backlog.

One of the challenges is that it introduces a UI component that we don't make use of anywhere else aside from Due Dates. All of the other capabilities that have allowed for icons have been components with icons that Trello already uses. We want to make sure we get this right and not accidentally make it easier for teams to build non Trello-y experiences.

Our hope is that at the point in time that custom fields is a core resource on the API, most use-cases for card-detail-badges will be covered. At that point we'll re-evaluate and make sure this makes sense.
