### ISSUE TITLE
Allow sending data uris for badge icons

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#105]
At the moment, Trello appends `?color=fff` or the like to the url we return for badges so that we know what color badge to render. We'd like to be able to render data uris that we generate on the client instead of having to generate them on a server and the query string addition prevents this.

It'd be great if we could return a function that took color as a parameter and returned a data-uri as a response. It'd probably need to call it for both possible colors given the iframe boundary. Alternatively, Trello could just detect that we sent a data-uri and not append the query string, but that would prevent us from being able to vary our badge color (which we do).

Thanks!

**Comment by bentleycook** [comment]
One of the initiatives we have underway is to bring Power-Ups to mobile. As we evaluate new feature requests, we're trying to be mindful that any that we add that are web-only may pre-clude them from being included on mobile.

We want to move towards a design that leans into using primarily structured data to communicate. So I don't think that adding support for client-side generated URIs makes sense for us right now.
