### ISSUE TITLE
trello adds 9.5 hours to due value

### ISSUE THREAD

**Issue by manishwy** [trello/api-docs#107]
I create a new card with due field set. Card is created but when I open it in trello I see the due time/date is off by 9.5 hours. I tried creating card first and then putting the due value even then I am having the same issue. My timezone offset is 5 hr 30mins. So I don't think thats an issue here.

Any suggestions what might be happening ?

**Comment by ludable** [comment]
Are you setting the value of the due date in ISO format? E.g. (JavaScript): new Date().toISOString()

**Comment by manishwy** [comment]
I was not converting it into ISO format. Did that and now its working fine :)

**Comment by bentleycook** [comment]
Thanks @ludable!

Adding a bit of documentation here: https://github.com/trello/api-docs/pull/109/commits/ea3caca54e81900dc61eceb71c8a9b4bbdf433a8
