### ISSUE TITLE
Get collections through API

### ISSUE THREAD

**Issue by jocelynduc** [trello/api-docs#108]
I need to get boards from a specific collection and I saw this post: http://stackoverflow.com/questions/40738809/how-to-get-collections-in-trello-api

Is there now a way to get collections through the API?

**Comment by bentleycook** [comment]
@jocelynduc I just added some documentation around them here: https://github.com/trello/api-docs/pull/110

Would love feedback as to whether the documentation makes sense or not.

**Comment by jocelynduc** [comment]
@bentleycook That is exactly what I was looking for. Your documentation makes sense and is easy to understand. Thank you
