### ISSUE TITLE
How to encode attachments for use via Trello web API 

### ISSUE THREAD

**Issue by AxelBellancourt** [trello/api-docs#111]
The file parameter documentation for the POST /1/cards/[card id or shortlink]/attachments API call does not specify how the file should be encoded. For "Valid Values" it simply says "A file". I was wondering if anyone has a working example of how to get files into Trello cards using the API.

The card is created but attachment is empty.

I tried everything, here is my code : 

var data = {file: "C://Users/User/Downloads/monfichier.docx", 
		  name: "name"};
		
		Trello.post('/cards/'+idCard+'/attachments', data, success, error);

**Comment by ludable** [comment]
You need to use multipart/form-data encoding, in which one of the parts contains the file. Although it's not too hard to put it together by hand, there's tons of libraries/modules to do this easily. Just make sure a part contains:

`
Content-Disposition: form-data; name=_ATTACHMENT_NAME_; filename=_ATTACHMENT_FILENAME_
Content-Type: _ATTACHMENT_MIME_TYPE_

_ATTACHMENT_BINARY_DATA_
`

**Comment by AxelBellancourt** [comment]
There is no way to simply attach a local file like they say in their example ? 

curl -D -X POST -F "file=@[path/to/file]" https://api.trello.com/1/cards/[cardId]/attachments?key=[yourKey]&token=[yourToken]

I thought my problem was with the syntax of the path

**Comment by ludable** [comment]
The -F option in curl sends content as multipart form data. From the documentation:

```
-F, --form <name=content>
              (HTTP) This lets curl emulate a filled-in form in which a user has pressed the submit button. This causes curl to POST data using the Content-Type multipart/form-
              data according to RFC 2388. This enables uploading of binary files etc. To force the 'content' part to be a file, prefix the file name with an @ sign. To just get
              the  content  part  from  a file, prefix the file name with the symbol <. The difference between @ and < is then that @ makes a file get attached in the post as a
              file upload, while the < makes a text field and just get the contents for that text field from a file.

              Example: to send an image to a server, where 'profile' is the name of the form-field to which portrait.jpg will be the input:

              curl -F profile=@portrait.jpg https://example.com/upload.cgi

              To read content from stdin instead of a file, use - as the filename. This goes for both @ and < constructs. Unfortunately it does not  support  reading  the  file
              from a named pipe or similar, as it needs the full size before the transfer starts.

              You can also tell curl what Content-Type to use by using 'type=', in a manner similar to:

              curl -F "web=@index.html;type=text/html" example.com

              or

              curl -F "name=daniel;type=text/foo" example.com

              You can also explicitly change the name field of a file upload part by setting filename=, like this:

              curl -F "file=@localfile;filename=nameinpost" example.com

              If filename/path contains ',' or ';', it must be quoted by double-quotes like:

              curl -F "file=@\"localfile\";filename=\"nameinpost\"" example.com

              or

              curl -F 'file=@"localfile";filename="nameinpost"' example.com

              Note that if a filename/path is quoted by double-quotes, any double-quote or backslash within the filename must be escaped by backslash.

              See further examples and details in the MANUAL.

              This option can be used multiple times.
```

**Comment by ludable** [comment]
Are you doing this in the browser or on node?

**Comment by AxelBellancourt** [comment]
in a chrome addon

**Comment by ludable** [comment]
You can read the file from the local filesystem?

**Comment by AxelBellancourt** [comment]
I'll check,
My aim is to attach a file that I find on website but I don't want to use "url" parameter because the link to the website is not always available.
The only way i found is too download the file and then use "file" parameter

**Comment by ludable** [comment]
You could try pre-filling a hidden form with an <input type="file" value="_path_"> field, and submitting it programmatically. Search for "submit a form using javascript".

**Comment by AxelBellancourt** [comment]
I'll try that, I think you are right I can't access my filesystem with my chrome extension

**Comment by ludable** [comment]
If you can't access the filesystem, then I doubt you'll be able to submit an arbitrary file from the filesystem using a hidden form. You may need to rethink the design of your extension.

**Comment by AxelBellancourt** [comment]
I think so, thank you Ludable

**Comment by pieterfeenstra** [comment]
Hello @AxelBellancourt and @ludable 

I'm really struggeling finding good examples for attachment file upload with multipart/form-data encoding and how to apply it to the API request.

adding a url attachment works, so it works partially but Im trying to attach a canvas converted to png.
but its not clear for me where the formdata  needs to be executed or inserted after file:?

hope that you can help me with a small example. 

my code that works for a simple url attachment
```
var newAttachment = { 
         url: 'http://www.trello.com'
}
Trello.post('/cards/'+ data.id+ '/attachments/' , newAttachment, creationAttachmentSucces);

```
attempt to  create form
```
// Content-Disposition: form-data;
              // name=ATTACHMENT_NAME;
              // filename=ATTACHMENT_FILENAME
              // Content-Type: ATTACHMENT_MIME_TYPE
              // ATTACHMENT_BINARY_DATA

              var formData = new FormData();

              formData.append("name", "myNote");
              formData.append("type" , "image/png")
              formData.append("file", downloadLinks[0]);
              // downloadLinks[0] is a canvas converted to binary using canvas.toDataURL()
              //  formData.append("file", downloadLinks[0]);


              var request = new XMLHttpRequest();
              // what url to use?
              request.open("POST", "https://api.trello.com/1/cards/" + data.id + '/attachments?key=2a210d78d852d792a4d8134c3de0581b');
              request.send(formData);



```

**Comment by ludable** [comment]
I'm not sure canvas.toDataURL() gives you the data in the right format. You probably need to create a Blob or File object to pass to append. Check out HTMLCanvasElement.toBlob(), although I'm not sure it's not supported in every browser.
What error do you get with your existing code?

**Comment by bentleycook** [comment]
@AxelBellancourt @pieterfeenstra I've put together a set of examples for multiple ways you can add attachments via the API here: [https://trello-attachments-api.glitch.me/](https://trello-attachments-api.glitch.me/). You can see all of the code used in this project here: [https://glitch.com/~trello-attachments-api](https://glitch.com/~trello-attachments-api).

Let me know if **anything** is unclear or if you'd like an example of something else!

**Comment by DieSwartKat** [comment]
@bentleycook I've tried your site, I cannot get it working. I am assuming that if I fill in the token, key and location to the image that it will execute it. Unless I'm missing something.

**Comment by bentleycook** [comment]
@DieSwartKat Yes, that should be all that you need to do. If you open the network tab in your browser's developer console do you see any error messages?

**Comment by DieSwartKat** [comment]
Thanks for the reply! I must have done something wrong. Thinking back I might have giving a list id instead of a card id.
I eventually got the code below working, although I'm using python 3.5.2 and not javascript:

```
def FiletoCard(key, token, image, cardid):
    params = (
        ('key', key),
        ('token', token),
    )

    files = {
        'file': (image, open(image, 'rb')),
    }

    response = requests.post('https://api.trello.com/1/cards/%s/attachments' % cardid, params=params, files=files)
    print(response.text)
    return response
```

**Comment by Darkmurat41** [comment]
access tokenslerinin third-part
