### ISSUE TITLE
Action event for list to board doesn't seem to fire?

### ISSUE THREAD

**Issue by jboe** [trello/api-docs#112]
I see that there's an action for moveListToBoard under Card Actions, but it doesn't seem to actually fire when a list is moved to another board. I tried looking for anything under the results of /actions?filter=all, but there doesn't appear to be anything for that either. When a card is moved to another list individually, it works fine with a moveCardToList and the new board/list ID, just doesn't seem to be firing with the movement of a whole list.

Thanks!

**Comment by ludable** [comment]
`moveListToBoard` is fired on the target board. You want to look for `moveListFromBoard` on the source board.

**Comment by bentleycook** [comment]
Closing this as @ludable provided the correct answer!
