### ISSUE TITLE
null mimeType after posting attachment to a card

### ISSUE THREAD

**Issue by iBicha** [trello/api-docs#119]
Posting an uploaded file as an attachment to a card, does not return a mimeType.

A POST request with the file. Node code:

```
function postAttachment(cardId, file) {
    return new Promise(function (resolve, reject) {
        var formData = {
            file: {
                value: <fileBuffer>,
                options: {
                    filename: <filename.ext>,
                    contentType: <file.mimetype>
                }
            }
        };
        request.post({
                url: 'https://api.trello.com/1/cards/' + cardId + '/attachments?key=' + <TRELLO_API_KEY> + '&token=' + <Token>,
                formData: formData
            },
            function (err, httpResponse, body) {
                if (!err) {
                    resolve(body)
                } else {
                    reject(err)
                }
            });
    })
}
```

**Expected result**
Json data about attachment with all fields.

**Actual result**
Json data about attachment with all fields (id, bytes, previews, etc) but mimeType is null

PS: the tested attachment is a png file, mimeType is set correctly, and trello recognize it as image.

**Comment by bentleycook** [comment]
@iBicha Have you taken a look at here: https://glitch.com/edit/#!/trello-attachments-api?path=public/client.js:29:2

Using it, I'm able to successfully post with this request body:

**Comment by iBicha** [comment]
Okey i think i figured this out. While the request module for node has a param for mimeType to set into the file object it self (contentType), i assumed trello would be able to pick that up, but no, the mimeType should be there as a param seperately (as stated in the docs, which i bizarrely missed, sorry)

So setting up the mimeType works, but i assumed it would be picked up from the contentType header. The way it is working right now is totally fine, but maybe can lead to inconsistency? (since on could put the wrong mime type manually)

Other than that, if this is the prefered behaviour, than there is no problem at all

**Comment by bentleycook** [comment]
👍 Glad you got it figured out! Holler if you run into any other questions.
