### ISSUE TITLE
The authentication example doesn't work... sometimes

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#127]
We have a user who has some security setting somewhere in Chrome checked that prevents accessing `window.opener.authorize` as recommended here: https://developers.trello.com/power-ups/topics#authentication

We've worked around it like this:

```js
let authorize

try {
  if (window.opener && typeof window.opener.authorize === 'function') {
    authorize = window.opener.authorize
  }
} catch (e) {
  // Security settings are preventing this, fall back to local storage.
}

if (authorize) {
  authorize(token)
} else {
  localStorage.setItem('token', token)
}
```

Of course, now we rely on localStorage being present, but what are the odds of both of those failing?!?!? 🙃

**Comment by bentleycook** [comment]
We've updated our docs and example projects (I believe we've gotten to all of them!) to use this flow.

https://developers.trello.com/power-ups/topics#authentication

Thanks!

**Comment by aaronjensen** [comment]
Sounds good, though I'm not seeing the update on that link or in this repo: https://github.com/trello/api-docs/blob/master/app/templates/power-ups/topics.html#L143

**Comment by bentleycook** [comment]
I misspoke, those never got changed.

Fixing here: https://github.com/trello/api-docs/pull/145/files
