### ISSUE TITLE
`billableMemberCount` is null for non-admins

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#128]
It seems that `billableMemberCount` from `/organizations/{id}/billableMemberCount` is null for non-admins. It seems we can still get the `billableMemberCount` just by querying `/organizations/{id}/memberships?filter=active` and counting them, so there's an inconsistency here. It'd be nice if we could just access `billableMemberCount`. Thanks!

**Comment by bentleycook** [comment]
This should be visible to anyone that is a member of the organization now.
