### ISSUE TITLE
Unable to create a checklist with n checkItems at once

### ISSUE THREAD

**Issue by cbarrerah** [trello/api-docs#132]
Hi, i'm trying to generate a checklist and populate it, and have created the checklist inside the desired card inside the desired list inside the desired board, but i'm unable to post the multiple checkItems at once.

Maybe a structure of POST call with a json in the body containing an array of checkItems? Sorry if this is already explained but i was unable to find it

posting this :
`[
  {
    "idChecklist": "5936d2ddd9c983e276f6fcc9",
    "name": "cosas"
  },
    {
    "idChecklist": "5936d2ddd9c983e276f6fcc9",
    "name": "secretas"
  }
]`
Resulted in a bad request response
`invalid value for name`

Any help or am I missreading the API doc?

Is there any better way to post several checkItems into a checkList in one API call?

Thanks in advance

**Comment by bentleycook** [comment]
@cbarrerah Unfortunately, there isn't a way to add multiple checklist items at once. You'll want to iterate through the items you want to add and add them one at a time.
