### ISSUE TITLE
Incompleted checklists

### ISSUE THREAD

**Issue by jocelynduc** [trello/api-docs#139]
I am fetching all the cards from a board and I would like to get the included checklists in the same request:

`Trello.get('boards/<board_id>/cards?actions=addChecklistToCard', success, error);`

Why this request only returns the completed checkItems? How to get all of them ?

If I fetch one of those cards with the following request, I get the incomplete checkitems as well:
`Trello.get('cards/<card_id>/checklists', success, error);`

**Comment by bentleycook** [comment]
@jocelynduc The first request you are making shouldn't be returning any `checkItems`. If you want to see all of the `checkItems` for all of the `checklists` on a single board, I'd recommend using the following call:
`Trello.get('boards/<board_id>/checklists/', success, error);`
