### ISSUE TITLE
Card cannot be created

### ISSUE THREAD

**Issue by ewugoat7** [trello/api-docs#141]
Am trying to create card but am having issues below
This is the code that I used to create card with my actual  API Key and Token
https://api.trello.com/1/cards?name=my first card&desc=my first decription&key=[my api key goes here]&token=[my token goes here]`

below is the error that am having..

Thanks

**Comment by bentleycook** [comment]
@ewugoat7 Did you mean to attach an image?

Please see comment on [previous issue](https://github.com/trello/api-docs/issues/140) for more help.

**Comment by ewugoat7** [comment]
okay I have seen that. but where can I get this idlist to post a card. this idlist does it belongs to board or what.

Do i have to create board before creating card. please clearify. Thanks

**Comment by bentleycook** [comment]
Yes, you need to have a board with a list on it to create a card. Where else would the card go? 😄 

You can get the `idList` via a number of API routes. I'd recommend starting with the [`1/boards/{idBoard}/lists`](https://developers.trello.com/advanced-reference/board#get-1-boards-board-id-lists) resource.

If you want to see what boards your user has, you can use: `1/members/me/boards`.
