### ISSUE TITLE
Is there a way to get only my personal boards?

### ISSUE THREAD

**Issue by ascandroli** [trello/api-docs#142]
Using the API I can get all my boards (_/1/members/me/boards?filter=open_), my starred boards (_T1/members/me/boards?filter=starred_), for each organization I belong to I can separately get its boards (/_1/organizations/[idOrg]/boards_), but I can't find a way to get only my personal boards. 

The only way I could find is to get all my boards and then iterate over the result and filter out the ones without the organization field.

Is there an API that allows me to get my personal boards?

**Comment by bentleycook** [comment]
@ascandroli There isn't a route to retrieve only your personal boards.

The best approach is the one you mentioned - listing all boards and filtering out those without an organization field or with idOrganization `null`.
