### ISSUE TITLE
Include display order of starred boards

### ISSUE THREAD

**Issue by paulkamer** [trello/api-docs#146]
At the moment, `/1/members/me/boards?filter=starred` returns all starred boards, in alphabetical order. The output doesn't seem to contain an attribute that reflects the sort order or how they are sorted in Trello itself.

Can the display/sort order of starred boards be included in the output?

**Comment by bentleycook** [comment]
@paulkamer You can see all of the starred boards and their positions via `/1/members/{memberId}/boardstars` documented [here](https://developers.trello.com/v1.0/reference#membersidboardstars).

Let me know if that doesn't cover your use-case.

**Comment by paulkamer** [comment]
@bentleycook thanks for your response. Yes that'll work, but it requires an additional API call. 

It would be great if that `pos` attribute can be included in the `/members/{id}/boards` response directly

**Comment by bentleycook** [comment]
Unfortunately, don't think we'll be able to add it because it is specific to the starred positioning. I'll pass along to the backend team though and update if that changes.
