### ISSUE TITLE
Ability to check on API rate limit

### ISSUE THREAD

**Issue by digitales** [trello/api-docs#147]
At the moment there doesn't seem to be an API endpoint for determining the number of requests remaining until the API rate limit is reached. 

Would it be possible either add additional headers to the API response and/or an extra API endpoint?

Example headers would be: 
`X-Rate-Limit-Limit` - The number of allowed requests in the current period
`X-Rate-Limit-Remaining` - The number of remaining requests in the current period
`X-Rate-Limit-Reset` - The number of seconds left in the current period

**Comment by JbalTero** [comment]
This will be useful.

**Comment by bentleycook** [comment]
Great idea! We've added them to the response from the server.

Documentation [here](https://developers.trello.com/v1.0/docs/rate-limits#section-rate-limits-in-headers).

**Comment by JbalTero** [comment]
Thanks
