### ISSUE TITLE
No (discoverable) way to find the raw HTTP API

### ISSUE THREAD

**Issue by meredydd** [trello/api-docs#148]
I have spent the last fifteen minutes scouring the documentation for how to access the API with a raw HTTP client, if I don't want to use the Javascript client library. It seems that this information is either very well hidden, or not there.

I have a token and an application key (do I need both? Who knows, the docs don't say!). I want to find out what hostname to hit (`api.trello.com`, perhaps? Who knows, the docs don't say!), and where to put the token (HTTP header? Query string parameter? Who knows, the docs don't say!)

Just one example of how to do something with `curl` would suffice - but I can't find anything except the Javascript client library.

**Comment by bentleycook** [comment]
@meredydd Thanks for the feedback.

We've recently updated our docs to be a bit easier to make example requests from. Now you should be able to make requests _inside_ of the docs. Give it a try at https://developers.trello.com/v1.0/reference#cardsid and share your feedback here. You _will_ need an API key and token and should be prompted to enter both (in addition to any required fields) when you click the "Try it" button on a resource.

**Comment by meredydd** [comment]
The new docs are superb. Bravo!
