### ISSUE TITLE
JavaScript examples use XMLHttpRequest.withCredentials which is not compatible with CORS access

### ISSUE THREAD

**Issue by philBrown** [trello/api-docs#150]
Example confusion here ~ https://stackoverflow.com/q/47985164/283366

Your [JavaScript examples](https://developers.trello.com/reference#cardsidmembers) have

```javascript
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;
```

which is not compatible with your `Access-Control-Allow-Origin` response header value of "*".

> The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

[`XMLHttpRequest.withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) allows local authentication data such as cookies to be used for access-control requests. Since all Trello API requests should include the `key` and `token` query parameters, I don't see a reason to set this at all.

**Comment by bentleycook** [comment]
@philBrown 🙈 Good catch. These are auto-generated by the docs tool we use, Readme.io. Unfortunately, not a way for us to change them. Working with them to see if we can't get it updated.

**Comment by bentleycook** [comment]
We've updated the examples so that they no longer set `withCredentials` to `true`.
