### ISSUE TITLE
Bug: Members are deleted when the due date is selected but when the user doesn't have photo

### ISSUE THREAD

**Issue by LeidyGil** [trello/api-docs#153]
In the web application the member selected is deleted when I select the due date. I must select the member again to save all the information; but this only happen when the user doesn't have profile photo, besides when the user set a profile photo the member is deleted of the all cards before assigned.

Steps:
-Log into web application
-Create a new card
-Click on card
-Select the member
-Close the card
-Open the card again
-Select the due date
-Set a profile photo

Actual Result: The member selected is deleted when I select the due date following the above steps.

**Comment by bentleycook** [comment]
@LeidyGil Sorry this is happening! This is an old repository for Trello's API documentation. You should send an email to support@trello.com and report the problem that you're having.
