### ISSUE TITLE
Endpoint /1/tokens/{YourToken}/webhooks only returns "unauthorized token"

### ISSUE THREAD

**Issue by rwilson0** [trello/api-docs#156]
I can register a webhook at the same endpoint but trying to issue a GET  results in "unauthorized token".

**Comment by bentleycook** [comment]
@rwilson0 Would you mind asking your question over here: https://community.developer.atlassian.com/c/trello

**Comment by bentley-atlassian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ok](https://trello.com/c/HLZ6eQ6N/681-ok)
