### ISSUE TITLE
addLabelToCard action not fired when adding label(s) to card on creation using #-notation

### ISSUE THREAD

**Issue by ludable** [trello/api-docs#47]
Steps to repro:

(1) Create a card adding a label using #-notation, e.g. "Test card will have a #green label"
(2) A createCard action is issued on the webhook, containing no details of the label.
(3) No addLabelToCard will be issued.

Worth documenting (if not fixing!)

**Comment by bentleycook** [comment]
The Trello web client is making use of the POST /1/cards/ resource and including the idLabels parameter. So this isn't just limited to the creation of a card via the web-clients #-notation shortcut.

**Comment by bentleycook** [comment]
This should be fixed. Can you give it a try?

**Comment by ludable** [comment]
Tested and verified. Disabling my workarounds now. Thanks!

**Comment by bentleycook** [comment]
👍 Awesome!
