### ISSUE TITLE
boards/<board_id>/checklists?cards=visible not supported

### ISSUE THREAD

**Issue by ludable** [trello/api-docs#56]
The [board resource documentation](https://developers.trello.com/advanced-reference/board#get-1-boards-board-id-checklists) specifies that when requesting a board's checklists, the cards can be requested alongside, with parameter _cards_, which can have valid values:

- all
- closed
- none
- open
- visible

In reality, requesting "visible" doesn't work, returning "Error: 400 invalid value for filter".

**Comment by bentleycook** [comment]
Fixed: https://github.com/trello/api-docs/commit/c7d690f666cc986c0218d48ca71bae62f054f61c

Thanks @ludable!
