### ISSUE TITLE
idLabels not being pulled on card creation

### ISSUE THREAD

**Issue by andrewbertrand** [trello/api-docs#69]
When applying labels objectid during a card creation, the value gets sent through jsonobj but is not applied to newly created cards on Trello. 

Does the card need to be created prior to applying a label?

**Comment by bentleycook** [comment]
You should be able to include a comma-seperated list of idLabels when POSTing to the _1/cards_ endpoint: https://developers.trello.com/advanced-reference/card#post-1-cards

Is that not working for you? If not, what response are you seeing?

**Comment by andrewbertrand** [comment]
Thanks for the response bentley, strangely I'm not getting any response code when passing the value but the rest of the card is posting fine. 

Here's a snippet of my code that's posting everything else fine (name, desc, due, member). :

` jsonObj = { name: $('#title').val(), desc: reqdesc, idList: idList, token: token, email: $('#emailadd').val(), due: dueDate, idMembers: member, idLabels: '5727bb68b0dfecc6d1231fc6'}; 

    Trello.post('/list/' + idList + '/cards', jsonObj, function(card) { 
      jsonObj['cardid'] = card.idShort; 
      if(jsonObj['cardid']) {
              
        var passData = encodeURIComponent(JSON.stringify(jsonObj)); `

My current work around is to run another post after the card is created.

**Comment by ludable** [comment]
@andrewbertrand Have you tried passing an array instead of a string?

**Comment by andrewbertrand** [comment]
thank @ludable, gave it a try with same results.

**Comment by bentleycook** [comment]
@andrewbertrand Unfortunately, we don't support adding labels via the `POST /1/lists/[idList]/cards` endpoint. However, you **can** add a label via `POST /1/cards/`. You'll want to include `idLabels` which should be an array of label IDs. Additionally, you can specify the list with `idList`. Full docs here: https://developers.trello.com/advanced-reference/card#post-1-cards

**Comment by andrewbertrand** [comment]
ah gotcha, thanks for your help.

**Comment by bentleycook** [comment]
Of course! Going to close this issue but holler if you have any other problems.
