### ISSUE TITLE
Can webhooks be registered for the user?

### ISSUE THREAD

**Issue by pke** [trello/api-docs#75]
I'd like to have only one webhook on the user model.
Would that be triggered whenever anything in the users boards, lists etc changes?

**Comment by bentleycook** [comment]
You can set a webhook on a user but that will only trigger POSTs when the user takes an action. The  action action object being created is what triggers the webhook.

If you want to watch specific boards, lists, and cards for changes, it is best to setup a webhook for those objects individually. However, a webhook on a board will catch changes to the cards and lists on it.

**Comment by pke** [comment]
So to watch a whole account I'd have to register hooks for all boards and the user? Imagine I have a dashboard that shows all recent activities across all boards. Or is the `Notification` model also watchable via webhook?

**Comment by bentleycook** [comment]
If you want to keep track of all of the activity across a set of boards, you'd want to setup a webhook for each of the boards. Setting up a webhook on a single user in addition to all of the boards would give you duplicate actions as the actions that user takes on the set of boards you are already watching should be captured by the webhooks on those boards.

An individual `Notification` object _can_ have a webhook setup on it, but that would only give you information about the single notification object and not _all_ notifications.

**Comment by nodje** [comment]
Why isn't it possible to create a webhook for a user's notification?
It seems a natural enough request, you classically want to have a handle on notifications for a specific user.
Would a webhook on a Member be triggered for each `notification` received ?
