### ISSUE TITLE
Can we link to another trello card?

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#77]
We'd like to be able to render links to other Trello cards in attachment sections and card detail badges. We can do it by specifying `_target="parent`, it works, but it opens a new browser tab for each click. We'd like to keep the user in the same tab. Is this possible?

By the way, is there a better place to ask questions than this?

**Comment by bentleycook** [comment]
@aaronjensen We thought this was a good thing to include in the Power-Ups API! So we're about to ship a feature that allows you to use the client-library to show a card.

I've got an issue open that shows the rough API. As soon as it goes live I'll update the docs: https://github.com/trello/api-docs/issues/79 Hopefully should ship in the next couple of days.

**Comment by aaronjensen** [comment]
That's awesome, we're looking forward to it, that'll help a lot.
