### ISSUE TITLE
Subscribing to changes / events?

### ISSUE THREAD

**Issue by SeanKilleen** [trello/api-docs#83]
Hi all,

After perusing the docs, I'm not quite sure how we should subscribe to Trello updates to take actions (or if that's a recommended / welcomed practice).

For example, let's say that when a card is moved to a list or archived, I'd like to call `t.set` to update a piece of data. Is that currently possible? And if so, what is the recommended approach? It appears that `render` might be the key, as it receives every `render` message, but I'm not sure whether `render` is received upon every board change or not. 

Thanks for clarifying. If the answer to this question ends up being useful to document, I'm happy to submit the subsequent information as a PR to the docs.

**Comment by SeanKilleen** [comment]
(also, thanks for a killer product.)

**Comment by bentleycook** [comment]
Hey @SeanKilleen, There isn't a way to receive updates within the Power-Up from the board. `t.render` only gets called within the context of the UI it is used in. Some of the capabilities do get re-called when objects relevant to them change. For example, `card-badges` when a card is moved.

What I think you're really wanting is webhooks: https://developers.trello.com/advanced-reference/webhook. They are going to offer you the most robust solution, I think. Given the use-case you shared, you could have a server that listens for a webhook, persists some data from it, and then your Power-Up could make a call to your server to retrieve that data when it needs it. A bit of a long-winded work-around, but I think that is the most fully-fledged option at the moment.

**Comment by SeanKilleen** [comment]
@bentleycook I see. My experiment was to see if I could create a dot voting powerup for trello cards, where a user has a number of votes, and those votes could be cleared when a card was archived, moved to a new list, etc.

Given that I don't want to spend money on a server setup at this point (was attempting to host it for free via github pages), it sounds like this might not be possible at this point -- or will be possible but points will need to be reclaimed manually. Does that sound correct?

**Comment by bentleycook** [comment]
Interesting. That would probably be easier with a backend, but I think you could make it work without one.

You could use **t.set** to store the id of the cards each member has voted for. And then when a user votes, you could check to see if they have used up all of their votes, and if they have, confirm that all of the ids that are stored are listed in a call to **t.cards** as it returns all open cards.

**Comment by SeanKilleen** [comment]
Perfect! Yep, my idea was definitely to use `t.set`, but I wanted to see about keeping both a user count and a per card count up to date returning votes. So it will just be a lot of extra checking at different times (init, when voting, when clearing votes from a card, etc.), but that's fine.

I think I'll be using `t.set` at the board level to update an array of (card + array[userId]). This way I can deduce the user votes left, and quickly count card votes.

**Comment by SeanKilleen** [comment]
Do I need to worry about timing conflicts if I take the above approach? For example, two people adding votes to a card near each other would both be calling `set` to update what will be the same variable (if taking my current approach). Dicey?

**Comment by SeanKilleen** [comment]
@bentleycook thanks! Deleted my prior comments as I think I have enough to take me forward and my thoughts had already evolved from there.

Thanks! Much appreciated.
