### ISSUE TITLE
Webhooks not firing when creating or updating a card

### ISSUE THREAD

**Issue by wyliethomas** [trello/api-docs#86]
Seems like our webhooks stopped working just over a week ago. Any changes to webhook events?

**Comment by bentleycook** [comment]
Hey @wyliethomas, is this for all of your webhooks or just one? Can you confirm that the token used is still valid and has not expired? Should be able to check via the token resource: https://developers.trello.com/advanced-reference/token?

**Comment by wyliethomas** [comment]
Thanks @bentleycook. It turned out to be a single webhook that was not working. The one I spot checked was also not configured right thats why I was thinking all of my webhooks were down. 

My tokens are good and I reset those 2 hooks and Im good to go. Thanks for your help!

y

**Comment by bentleycook** [comment]
Awesome! Glad you figured it out. Holler anytime in the future if you need help. Happy to help!
