### ISSUE TITLE
card-detail-badges with callback

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#88]
Hi,

It doesn't seem to be documented, but it does seem that you can use callbacks with card-detail-badges. This is great as we're using the new `t.showCard` api. Unfortunately, I can't figure out how to `preventDefault` to prevent the link from being clicked when the user clicks on the badge. Any ideas?

Thanks!

**Comment by bentleycook** [comment]
Are you creating a card-detail-badge with a URL? If so, do you need the URL if you are using a callback?

```
'card-detail-badges': function(t, options) {
    return [{
      title: 'My Detail Badge', // for detail badges only
      text: 'Popup',
      callback: function(context) { // function to run on click
        return context.popup({
          title: 'Card Detail Badge Popup',
          url: './settings.html'
        });
      }
    }]
  },
```

**Comment by aaronjensen** [comment]
We were, yes. I have removed it for now. If you watch the url bar even in your scenario, I believe it updates to `<oldurl>#` because the link the callback is on has an `href="#"`. It should probably `preventDefault` w/in the onClick if there's a callback. 

We would prefer to have the url and the callback because it is semantically a link to another card. We use `t.showCard` to go to the card in the callback, but would still want to support "Open in new tab".

**Comment by bentleycook** [comment]
@aaronjensen Just deployed the code change that includes `preventDefault`. Give it a try and let me know if it works as you'd expect.

**Comment by aaronjensen** [comment]
@bentleycook it works perfectly, thank you.
