### ISSUE TITLE
Access the root board (Team board) with API

### ISSUE THREAD

**Issue by prao11788** [trello/api-docs#99]
Hi 

When you setup an account you get personal board. You can create a team board to collaborate with members in your team. Using the API I need to create a boards within the team board, what is the API endpoint to do it. In the attached screenshot, I need to create a board within the ABC Firm.

![trelloboard](https://cloud.githubusercontent.com/assets/27497002/25044426/a95b102e-20f4-11e7-9533-1c2bdf315d8a.PNG)

**Comment by bentleycook** [comment]
Hey @prao11788,

You'd want to use the POST /1/boards resource as documented here: https://developers.trello.com/advanced-reference/board#post-1-boards. To add the board to an organization, pass the id of the organization to which the board should be added as a query parameter: ?idOrganization=yourOrganizationsId
